language: ruby

before_script:
- chmod +x ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

cache: bundler

script:
- ./scripts/cibuild

notifications:
  email:
    recipients:
      - garrett@jansen.sh
    on_success: never
    on_failure: always