language: ruby
rvm:
- 2.4.1

before_script:
- chmod +x ./scripts/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

cache: bundler

script:
- ./scripts/cibuild.sh

notifications:
  email:
    recipients:
      - garrett@jansen.sh
    on_success: never
    on_failure: always
