language: ruby
rvm:
- 2.4.1
addons:
  ssh_known_hosts: 69.164.214.227
before_install:
- openssl aes-256-cbc -K $encrypted_dc7da2cdae2e_key -iv $encrypted_dc7da2cdae2e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- bundle install
- gem install jekyll
- gem install html-proofer
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
    - garrett@jansen.sh
    on_success: never
    on_failure: always
sudo: false
cache: bundler
before_script:
- chmod +x ./_scripts/build.sh
script: _scripts/build.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash _scripts/deploy.sh
  on:
    branch: master
