language: ruby
rvm:
- 2.4.1

before_script:
  - chmod +x _scripts/build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

cache: bundler

script: sh _scripts/build.sh

notifications:
  email:
    recipients:
      - garrett@jansen.sh
    on_success: never
    on_failure: always