# General Settings
name: Garrett Jansen
job_title: Security, Linux and the Cloud
email: garrett@jansen.sh
description: I work to build a better internet for all. Currently, Senior Developer Support Engineer at DigitalOcean and Cybersecurity Graduate student with a Cyberterrorism focus at Wilmington University. All opinions are my own.
avatar: /assets/img/avatar.jpg
favicon: /favicon.ico
twitter_handler: slavexstate 
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'https://twitter.com/jansendotsh' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/garrett-jansen/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://www.github.com/jansendotsh/' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: 'https://open.spotify.com/user/garrettjansen' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://jansen.sh"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

responsive_image:
  template: _includes/picture.html
